### PR TITLE
tweaks and tunings

### PR DESCRIPTION
**Pull request by vnglst**

### CODE REVIEW

**Comment by pranaygp** [comment]
Hey @vnglst.
It seems like you're running into this issue because `files` in `now.json` is a strict whitelist, so make sure you include all the files you'd like to have in your deployment. 

You can also read more about it here https://zeit.co/docs/features/configuration

Also, we apologise for the cryptic error message since we we just rolled this feature out, but we're working on having better error messages here too :D

In the meanwhile feel free to email us or reach out at https://zeit.chat if you run into an issue with an unexpected error code and we can help out

**Comment by vnglst** [comment]
Hi @pranaygp! Thanks for reaching out. I'm trying to deploy a static website here (build folder `./build`. Any tips on how to do this?

**Comment by pranaygp** [comment]
@vnglst, is it possible you forgot to build your app to generate the build folder? Also, you may want to consider using the "static" configuration in `now.json` to select the build folder specifically. https://zeit.co/docs/features/configuration#static(object)

Also, since you already have a "build" and "start" script in your "package.json" file, you can try to make a regular npm deployment by removing the "files" key completely

**Comment by pranaygp** [comment]
Oh, I see in your latest commit you already used the static configuration. Now also respects your .gitignore file, which means the "build" folder is getting ignored. You might want to try using the "files" key as well to keep those files in your deployment

**Comment by pranaygp** [comment]
@vnglst it seems upon further inspection that your "build" dir never reaches Now regardless of your `now.json` config. This actually makes sense because `.gitignore` specifically ignores that directory, and so it never reaches GitHub, and therefore Now can never retrieve those files.

Instead, you could try to just make a regular `npm` deployment by removing the "static" and "files" properties from your config. This will make it so your projec is built and run on Now using your predefined `build` and `start` scripts.

**Comment by vnglst** [comment]
@pranaygp ah haha, yes makes sense.

I'm not sure using the `build` and `start` script is going to work, the latter starts a development server. I think I'll stick with Netlify for this right now, but thanks for your time and help!

**Comment by pranaygp** [comment]
Always a pleasure @vnglst 🤗

**Pull request merged**
